### PR TITLE
Issue upgrades

### PR DESCRIPTION
**Pull request by ocarriles**
Persistence, Authorization/Authentication, REST stuff in place

### CODE REVIEW

**Comment by deruelle** [comment]
I merged it and will try to review but reviewing 60 Files change is difficult in context of the open issued. Let's try to do one pull request per issue from now on.

**Comment by ocarriles** [comment]
sorry I know, I had lot of stuff unpushed and was so difficult to separate pieces without breaking code.
One pull/One issue now on :)

**Comment by ocarriles** [comment]
@deruelle  Making more than one pull request without waiting for your reviews breaks the one pull/one issue contract?

**Comment by deruelle** [comment]
I think that's fine if in each commit you reference the Issue you're fixing/updating.
See the IMPORTANT Sections in https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit#heading=h.yvg5944rd9wk

**Pull request merged**
